import Link from "next/link";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";

type Props={data:any;styles:Record<string,string>};
const sectionTypes=["overview","checklist","video","benefits","documents","process","pricing","related","expert","faq"] as const;

function Section({type,data,styles}:{type:any;data:any;styles:Record<string,string>}){
  if(type==='overview')return <section className={styles.section}><div className={styles.sectionLead}><span>01 · OVERVIEW</span><h2>Know what this service is solving.</h2></div><div className={styles.copyGrid}>{data.overview.map((x:string,i:number)=><p key={i}>{x}</p>)}</div><div className={styles.highlightStrip}>{data.highlights.map((x:string)=><span key={x}>{x}</span>)}</div></section>;
  if(type==='checklist')return <section className={styles.section}><div className={styles.sectionLead}><span>02 · PREPARE</span><h2>Get the right information ready.</h2><p>Start with the details that make the next stage easier to review.</p></div><div className={styles.checkGrid}>{data.checklist.map((x:any,i:number)=><article key={i}><b>{String(i+1).padStart(2,'0')}</b><div><h3>{x[0]}</h3><p>{x[1]}</p></div></article>)}</div></section>;
  if(type==='video')return <section className={styles.section}><div className={styles.videoCard}><div><span>03 · EXPERT WALKTHROUGH</span><h2>Understand the journey before you commit.</h2><p>Use this area for the approved expert tutorial when the video asset is available.</p><button type="button">Play walkthrough <span>↗</span></button></div><div className={styles.videoFrame}><div className={styles.play}>▶</div><small>LAWXYGEN · EXPERT VIDEO</small></div></div></section>;
  if(type==='benefits')return <section className={styles.section}><div className={styles.sectionLead}><span>04 · BENEFITS</span><h2>What a clearer workflow gives you.</h2></div><div className={styles.benefitGrid}>{data.benefits.map((x:any,i:number)=><article key={i}><span>{String(i+1).padStart(2,'0')}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></section>;
  if(type==='documents')return <section className={styles.section}><div className={styles.sectionLead}><span>05 · DOCUMENTS</span><h2>Keep the file easy to review.</h2></div><div className={styles.docList}>{data.documents.map((x:any,i:number)=><article key={i}><div className={styles.docNo}>{String(i+1).padStart(2,'0')}</div><div><h3>{x[0]}</h3><p>{x[1]}</p></div><span>＋</span></article>)}</div></section>;
  if(type==='process')return <section className={styles.section}><div className={styles.processHeader}><div><span>06 · PROCESS</span><h2>From first request to a clear finish.</h2></div><p>Each step is intentionally concise so a user can understand the route without reading a wall of text.</p></div><div className={styles.processRail}>{data.process.map((x:any,i:number)=><article key={i}><b>{x[0]}</b><p>{x[1]}</p></article>)}</div></section>;
  if(type==='pricing')return <section className={styles.section}><div className={styles.pricingCard}><div><span>07 · PRICING</span><h2>Keep the commercial step transparent.</h2><p>Connect the client-approved fee or package here when final pricing is supplied.</p></div><div className={styles.pricePanel}><small>LAWXYGEN SUPPORT</small><strong>Custom quote</strong><span>Scope, urgency and professional involvement can change the final fee.</span><button type="button">Request pricing <span>→</span></button></div></div></section>;
  if(type==='related')return <section className={styles.section}><div className={styles.sectionLead}><span>08 · RELATED SERVICES</span><h2>Continue with something connected.</h2></div><div className={styles.relatedRow}>{data.related.map((x:any)=><Link href={x.href} key={x.title}><span>{x.title}</span><b>↗</b></Link>)}</div></section>;
  if(type==='expert')return <section className={styles.section} id="expert"><div className={styles.expertCard}><div><span>09 · NEED HELP?</span><h2>Bring in the right professional.</h2><p>Use LAWXYGEN to route a case-specific question to the appropriate lawyer, CA, CS or specialist.</p></div><div className={styles.expertActions}><Link href="/login">Sign in <span>→</span></Link><Link href="/">Talk to an expert <span>↗</span></Link></div></div></section>;
  return <section className={styles.section}><div className={styles.sectionLead}><span>10 · FAQ</span><h2>Questions worth answering early.</h2></div><div className={styles.faq}>{data.faqs.map((x:any,i:number)=><details key={i}><summary>{x[0]}<span>＋</span></summary><p>{x[1]}</p></details>)}</div></section>;
}

export function ServicePageTemplate({data,styles}:Props){
  const order=([['overview','checklist','video','benefits','documents','process','pricing','related','expert','faq']])[0];
  const variant=data.variant%24;
  const orders=[
   ['overview','checklist','video','benefits','documents','process','pricing','related','expert','faq'],['overview','benefits','documents','process','checklist','video','related','pricing','faq','expert'],['overview','process','checklist','documents','benefits','pricing','video','expert','related','faq'],['overview','documents','video','benefits','checklist','process','related','faq','pricing','expert'],['overview','checklist','process','video','benefits','pricing','documents','expert','faq','related'],['overview','benefits','checklist','process','video','documents','pricing','related','expert','faq'],['overview','video','documents','checklist','benefits','expert','process','pricing','faq','related'],['overview','documents','process','benefits','video','checklist','related','expert','pricing','faq'],['overview','checklist','benefits','documents','process','video','expert','pricing','related','faq'],['overview','process','video','checklist','documents','benefits','pricing','faq','expert','related'],['overview','benefits','process','documents','checklist','video','related','expert','faq','pricing'],['overview','documents','checklist','benefits','video','pricing','process','related','faq','expert'],['overview','video','benefits','process','checklist','documents','expert','related','pricing','faq'],['overview','checklist','documents','pricing','benefits','process','video','faq','related','expert'],['overview','process','benefits','checklist','documents','video','pricing','expert','related','faq'],['overview','documents','benefits','video','checklist','pricing','process','expert','faq','related'],['overview','benefits','video','process','documents','checklist','related','pricing','expert','faq'],['overview','checklist','video','process','benefits','related','documents','pricing','faq','expert'],['overview','documents','process','video','benefits','pricing','checklist','related','expert','faq'],['overview','process','documents','benefits','video','expert','checklist','pricing','faq','related'],['overview','benefits','documents','checklist','process','pricing','video','related','faq','expert'],['overview','video','checklist','documents','benefits','process','expert','related','pricing','faq'],['overview','process','benefits','video','documents','checklist','faq','pricing','related','expert'],['overview','documents','checklist','process','video','benefits','related','faq','expert','pricing']
  ][variant];
  const vars={"--accent":data.accent,"--page-bg":data.bg,"--soft":data.soft} as React.CSSProperties;
  return <><Header/><main className={`${styles.page} ${styles[`layout${variant}`]}`} style={vars}><div className={styles.topSpace}/><div className={styles.breadcrumb}><Link href="/">Home</Link><span>•</span><Link href="/services">Services</Link><span>•</span><span>{data.category}</span><span>•</span><strong>{data.title}</strong></div><section className={styles.hero}><div className={styles.heroMain}><span className={styles.kicker}>{data.category} · LAWXYGEN</span><h1>{data.title}</h1><p>{data.summary}</p><div className={styles.heroActions}><Link href="/login" className={styles.primary}>{data.cta}<span>↗</span></Link><a href="#expert" className={styles.secondary}>Talk to an expert <span>→</span></a></div><div className={styles.heroMeta}>{data.highlights.map((x:string)=><span key={x}>{x}</span>)}</div></div><aside className={styles.dashboard}><div className={styles.dashTop}><span>CLIENT WORKSPACE</span><b>01</b></div><h2>Keep the next action visible.</h2><div className={styles.status}><div><span>Category</span><strong>{data.category}</strong></div><div><span>Service</span><strong>{data.title}</strong></div><div><span>Status</span><strong>Ready to start</strong></div><div><span>Next</span><strong>Review requirements</strong></div></div><Link href="/login" className={styles.dashButton}>Login / Sign up <span>→</span></Link></aside></section><nav className={styles.index}><span>INDEX</span>{order.map((x,i)=><a href={`#s-${x}`} key={x}>{String(i+1).padStart(2,'0')} {x}</a>)}</nav><div className={styles.bodyLayout}><aside className={styles.sideIndex}><div><small>ON THIS PAGE</small>{order.map((x,i)=><a href={`#s-${x}`} key={x}><b>{String(i+1).padStart(2,'0')}</b>{x}</a>)}</div></aside><div className={styles.content}>{order.map(type=><div id={`s-${type}`} key={type}><Section type={type} data={data} styles={styles}/></div>)}</div></div><div className={styles.footerNote}><span>LAWXYGEN</span><p>{data.note}</p></div></main><Footer/></>;
}
